from sqlalchemy import (
    Column,
    Integer,
    String,
    DateTime,
    ForeignKey,
    Text
)

from sqlalchemy.orm import relationship

from datetime import datetime

from app.config.database import Base


class AuditLog(Base):

    __tablename__ = "audit_logs"


    # =====================================================
    # Primary Key
    # =====================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )


    # =====================================================
    # Company / Tenant
    # =====================================================

    company_id = Column(
        Integer,
        ForeignKey("companies.id"),
        nullable=False,
        index=True
    )


    # =====================================================
    # User who performed the action
    # =====================================================

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )


    # =====================================================
    # Action
    # Example:
    # LOGIN
    # LOGOUT
    # CREATE
    # UPDATE
    # DELETE
    # STOCK_ADJUSTMENT
    # IMPORT
    # EXPORT
    # =====================================================

    action = Column(
        String(100),
        nullable=False,
        index=True
    )


    # =====================================================
    # Resource Type
    # Example:
    # Product
    # Customer
    # User
    # Inventory
    # Category
    # =====================================================

    resource_type = Column(
        String(100),
        nullable=True,
        index=True
    )


    # =====================================================
    # Resource ID
    # Example:
    # Product ID = 1024
    # Customer ID = 25
    # =====================================================

    resource_id = Column(
        Integer,
        nullable=True,
        index=True
    )


    # =====================================================
    # Description
    # Example:
    # "Product status changed from Active to Inactive"
    # =====================================================

    description = Column(
        Text,
        nullable=True
    )


    # =====================================================
    # Before Values
    #
    # Stores the old values for important updates.
    #
    # Example:
    # {
    #     "status": "Active",
    #     "price": 5000
    # }
    #
    # Stored as JSON text for now.
    # =====================================================

    before_values = Column(
        Text,
        nullable=True
    )


    # =====================================================
    # After Values
    #
    # Stores the new values for important updates.
    #
    # Example:
    # {
    #     "status": "Inactive",
    #     "price": 5500
    # }
    # =====================================================

    after_values = Column(
        Text,
        nullable=True
    )


    # =====================================================
    # IP Address
    #
    # Captured by backend from the request.
    # =====================================================

    ip_address = Column(
        String(50),
        nullable=True
    )


    # =====================================================
    # User Agent
    #
    # Stores browser/device information.
    # =====================================================

    user_agent = Column(
        String(500),
        nullable=True
    )


    # =====================================================
    # Status
    #
    # Examples:
    # Success
    # Failed
    # =====================================================

    status = Column(
        String(50),
        nullable=False,
        default="Success",
        index=True
    )


    # =====================================================
    # Timestamp
    #
    # Automatically generated by backend.
    # =====================================================

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )


    # =====================================================
    # Relationships
    # =====================================================

    company = relationship(
        "Company",
        back_populates="audit_logs"
    )


    user = relationship(
        "User",
        back_populates="audit_logs"
    )